### ISSUE TITLE
Tweaks: Error when loading mods offline

### ISSUE THREAD

**Issue by afyber** [samfundev/KTANE-Mods#25]
When I try to enable mods while not connected to the internet, something you can do normally. If the Tweaks mod is enabled the game freezes with this error message:
```
[Unity] Exception: NullReferenceException: Object reference not set to an instance of an object 
at: DemandBasedLoading+<GetModules>d__20.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
```
EDIT: As you might expect from the error message this only occurs with demand based mod loading on

**Comment by samfundev** [comment]
I think this has been fixed with 9d7c99457d2f3aa4682c7273959fd44640463266. If not, feel free to reopen.
